apiVersion: 1

# Automatically provision Loki as the default data source so log dashboards
# are ready as soon as Grafana starts.
datasources:
  - name: Loki
    type: loki
    uid: storyflow-loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    jsonData:
      maxLines: 1000
    editable: true
